### ISSUE TITLE
Unable to use gableroux/unity3d:2019.3.13f1-update-2020-05-07 (docker container does not exists)

### ISSUE THREAD

**Issue by loic-lopez** [game-ci/unity-request-activation-file#41]
Hi,

I'm using the latest stable 2019.3.x version of Unity but the docker container is only provided with the following version : **2019.3.13f1-update-2020-05-07** and of course after setting the variable `unityVersion` in my yml file I'm getting error for generating the licence file.

You can see the logs at: [loic-lopez/UMVC/runs/657049541](https://github.com/loic-lopez/UMVC/runs/657049541?check_suite_focus=true)

And the .yml file at: [loic-lopez/UMVC/actions/runs/99337511/workflow](https://github.com/loic-lopez/UMVC/actions/runs/99337511/workflow)

**Comment by webbertakken** [comment]
Hi @loic-lopez and thank you for your report.

Configuring the version like you have in your action will not work, because the action is [parsing](https://github.com/webbertakken/unity-builder/blob/master/src/model/image-tag.js#L74) the docker tag based on what platform you want to build for. 

Docker image [2019.3.13f1](https://hub.docker.com/r/gableroux/unity3d/tags?page=1&name=2019.3.13f1) seems to only have 1 Image that is not prepared for building any platform (which you can see by the lack of `-platform` part in the tag. 

I understand the confusion, but I think this is an experimental image that can not be used as is. You can see the related [merge request](https://gitlab.com/gableroux/unity3d/-/merge_requests/110) from @GabLeRoux and ask more about the image. But so far it seems to not yet be merged.

**Comment by loic-lopez** [comment]
Thanks I will downgrade to 2019.3.12f1 so 🥇 

Have a nice day.
